
export const TELUGU_TRANSLATIONS: Record<string, string> = {
  // Common instructions
  "Stand with feet shoulder-width apart.": "మీ పాదాలను భుజాల వెడల్పులో ఉంచి నిలబడండి.",
  "Lower your hips as if sitting in a chair.": "కుర్చీలో కూర్చున్నట్లుగా మీ నడుమును కిందకు దించండి.",
  "Keep your chest up and back straight.": "మీ ఛాతీని పైకి ఉంచి, వెన్నుముకను నిటారుగా ఉంచండి.",
  "Push through your heels to stand back up.": "తిరిగి పైకి లేవడానికి మీ మడమలపై ఒత్తిడి తీసుకురండి.",
  "Face a wall and place hands at shoulder height.": "గోడ వైపు తిరిగి మీ చేతులను భుజాల ఎత్తులో ఉంచండి.",
  "Lean in until your chest nearly touches the wall.": "మీ ఛాతీ గోడకు తగిలే వరకు ముందుకు వంగండి.",
  "Push back to the starting position.": "మళ్ళీ పాత స్థితికి వెనక్కి నెట్టండి.",
  "Keep your body in a straight line.": "మీ శరీరాన్ని సరళ రేఖలో ఉంచండి.",
  "Start on your forearms and toes.": "మీ ముంజేతులు మరియు కాలి వేళ్లపై ప్రారంభించండి.",
  "Keep your body straight from head to heels.": "తల నుండి మడమల వరకు మీ శరీరాన్ని నిటారుగా ఉంచండి.",
  "Engage your core and squeeze your glutes.": "మీ పొట్ట కండరాలను మరియు పిరుదులను గట్టిగా పట్టండి.",
  "Hold without letting your hips sag.": "నడుము కిందకు జారకుండా పట్టుకోండి.",
  "Hold a weight (or water bottle) close to your chest.": "మీ ఛాతీకి దగ్గరగా ఒక బరువును పట్టుకోండి.",
  "Squat down deeply while keeping the weight stable.": "బరువును స్థిరంగా ఉంచుతూ లోతుగా కూర్చోండి.",
  "Keep your elbows inside your knees at the bottom.": "కూర్చున్నప్పుడు మీ మోచేతులను మోకాళ్ల లోపల ఉంచండి.",
  "Stand up forcefully while bracing your core.": "పొట్టను బిగబట్టి బలంగా పైకి లేవండి.",
  "Start in a high plank position on the floor.": "నేలపై హై ప్లాంక్ స్థితిలో ప్రారంభించండి.",
  "Lower your chest until it's just above the ground.": "మీ ఛాతీ నేలకు తగిలేంత వరకు కిందకు దించండి.",
  "Push back up to the starting position.": "మళ్ళీ పాత స్థితికి పైకి నెట్టండి.",
  "Keep your core tight and elbows at 45 degrees.": "పొట్టను గట్టిగా ఉంచి, మోచేతులను 45 డిగ్రీల కోణంలో ఉంచండి.",
  "Bend forward slightly at the hips with a flat back.": "వెన్నుముక నిటారుగా ఉంచి నడుము వద్ద కొద్దిగా ముందుకు వంగండి.",
  "Pull the weight toward your hip, squeezing your shoulder blade.": "భుజం ఎముకను నొక్కుతూ బరువును మీ నడుము వైపు లాగండి.",
  "Lower the weight with control.": "నియంత్రణతో బరువును కిందకు దించండి.",
  "Switch arms and repeat.": "మరో చేతితో మార్చి మళ్ళీ చేయండి.",
  "Start in a pushup position.": "పుషప్ స్థితిలో ప్రారంభించండి.",
  "Drive one knee toward your chest rapidly.": "ఒక మోకాలిని మీ ఛాతీ వైపు వేగంగా తీసుకురండి.",
  "Switch legs in a running motion.": "పరుగు తీస్తున్నట్లుగా కాళ్లను మార్చండి.",
  "Keep your hips low and core engaged.": "నడుమును కిందకు ఉంచి పొట్ట కండరాలను బిగబట్టండి.",
  "Drop into a squat and place hands on the floor.": "స్క్వాట్ స్థితిలోకి వచ్చి చేతులను నేలపై ఉంచండి.",
  "Kick your feet back into a pushup position.": "కాళ్లను వెనక్కి నెట్టి పుషప్ స్థితిలోకి రండి.",
  "Do a pushup, then jump your feet back to your hands.": "ఒక పుషప్ చేసి, కాళ్లను చేతుల దగ్గరకు తీసుకురండి.",
  "Explode into a jump with hands overhead.": "చేతులను పైకి ఎత్తి గాలిలోకి దూకండి.",
  "Position a bar across your upper back (use a stick for practice).": "మీ వెనుక భాగంలో ఒక బార్‌ను ఉంచండి.",
  "Squat down until thighs are parallel to the floor.": "మీ తొడలు నేలకు సమాంతరంగా ఉండే వరకు కూర్చోండి.",
  "Drive back up through your heels.": "మీ మడమలతో బలంగా పైకి లేవండి.",
  "Keep your spine neutral and core braced.": "వెన్నుముకను మామూలుగా ఉంచి పొట్టను బిగబట్టండి.",
  "Grip the bar slightly wider than shoulders.": "భుజాల కంటే కొంచెం వెడల్పుగా బార్‌ను పట్టుకోండి.",
  "Pull yourself up until your chin clears the bar.": "మీ గడ్డం బార్‌ను దాటే వరకు పైకి లాగండి.",
  "Lower yourself with full control.": "పూర్తి నియంత్రణతో మిమ్మల్ని మీరు కిందకు దించుకోండి.",
  "Avoid swinging or using momentum.": "ఊగడం లేదా ఊపును ఉపయోగించడం మానుకోండి.",
  "Hang from a bar with arms straight.": "చేతులు తిన్నగా ఉంచి బార్‌ నుండి వేలాడండి.",
  "Raise your legs until they are parallel to the floor.": "మీ కాళ్లు నేలకు సమాంతరంగా ఉండే వరకు పైకి ఎత్తండి.",
  "Lower them slowly to avoid swinging.": "ఊగకుండా ఉండటానికి వాటిని మెల్లగా కిందకు దించండి.",
  "Focus on using your lower abs.": "క్రింది పొట్ట కండరాలను ఉపయోగించడంపై దృష్టి పెట్టండి.",
  "Focus on quality sleep (7-9 hours).": "7 నుండి 9 గంటల నాణ్యమైన నిద్రపై దృష్టి పెట్టండి.",
  "Stay hydrated throughout the day.": "రోజంతా తగినంత నీరు తాగుతూ ఉండండి.",
  "Light walking is optional but recommended.": "తేలికపాటి నడక ఐచ్ఛికం కానీ మంచిది.",
  "Eat nutrient-dense whole foods.": "పోషకాలు ఉన్న ఆహారాన్ని తీసుకోండి.",
  "Find a quiet, comfortable space.": "నిశ్శబ్దంగా, సౌకర్యవంతంగా ఉండే స్థలాన్ని ఎంచుకోండి.",
  "Hold each stretch for at least 30 seconds.": "ప్రతి స్ట్రెచ్‌ను కనీసం 30 సెకన్ల పాటు పట్టుకోండి.",
  "Focus on deep, rhythmic breathing.": "లోతైన శ్వాస తీసుకోవడంపై దృష్టి పెట్టండి.",
  "Never stretch to the point of pain.": "నొప్పి కలిగేంత వరకు స్ట్రెచ్ చేయవద్దు.",
  "Start in a standing position (Mountain Pose).": "నిలబడి (మౌంటైన్ పోజ్) ప్రారంభించండి.",
  "Slowly transition through basic poses like Downward Dog.": "డౌన్‌వర్డ్ డాగ్ వంటి ప్రాథమిక పోజ్‌లలోకి నెమ్మదిగా మారండి.",
  "Coordinate your movements with your breath.": "మీ కదలికలను శ్వాసతో సమన్వయం చేసుకోండి.",
  "Focus on balance and gentle elongation.": "సమతుల్యత మరియు శరీరాన్ని సాగదీయడంపై దృష్టి పెట్టండి.",
  "Feet shoulder width.": "పాదాలను భుజాల వెడల్పులో ఉంచండి.",
  "Back straight.": "వెన్నుముకను నిటారుగా ఉంచండి.",
  "On knees.": "మోకాళ్లపై ఉండండి.",
  "Body straight.": "శరీరాన్ని తిన్నగా ఉంచండి.",
  "On all fours.": "రెండు చేతులు మరియు మోకాళ్లపై ఉండండి.",
  "Opposite arm/leg.": "వ్యతిరేక దిశలో చేయి మరియు కాలును చాచండి.",
  "Hold weight at chest.": "బరువును ఛాతీ దగ్గర పట్టుకోండి.",
  "Deep squat.": "లోతుగా కూర్చోండి.",
  "Single leg.": "ఒంటి కాలిపై ఉండండి.",
  "Balance.": "సమతుల్యతను పాటించండి.",
  "Raise legs.": "కాళ్లను పైకి ఎత్తండి.",
  "Keep arms straight.": "చేతులను తిన్నగా ఉంచండి."
};

export const translateInstruction = (text: string, lang: 'en' | 'te'): string => {
  if (lang === 'en') return text;
  return TELUGU_TRANSLATIONS[text] || text; // Fallback to English if no translation
};
